texts = {
    "en": {
        "title": "Average temperature in %s was %.1f°C over the last 24 hours",
        "warm": "warm",
        "hot": "hot",
        "very hot": ", very %s",
        "pretty hot": ", pretty %s",
        "average": ", about average",
        "pretty cold": ", pretty cold",
        "very cold": ", very cold",
        "early": "early ",
        "late": "late ",
        "mid": "mid-",
        "for month": " for %s%s",
        "Jan": "January",
        "Feb": "February",
        "Mar": "March",
        "Apr": "April",
        "May": "May",
        "Jun": "June",
        "Jul": "July",
        "Aug": "August",
        "Sep": "September",
        "Oct": "October",
        "Nov": "November",
        "Dec": "December",
        "annotate_avg": "%d-1999 average daily temperature (%s weather station)",
        "annotate_lastweek": "Average daily temperature for the last week",
        "source": "Data source",
        "record": "new record"
    },
    "fr": {
        "title": "La température moyenne à %s était de %.1f°C au cours des dernières 24 heures",
        "warm": "doux",
        "hot": "chaud",
        "very hot": ", très %s",
        "pretty hot": ", assez %s",
        "average": ", proche de la moyenne",
        "pretty cold": ", plutôt froid",
        "very cold": ", très froid",
        "early": "début ",
        "late": "fin ",
        "mid": "mi-",
        "for month": " pour %s%s",
        "Jan": "janvier",
        "Feb": "février",
        "Mar": "mars",
        "Apr": "avril",
        "May": "mai",
        "Jun": "juin",
        "Jul": "juillet",
        "Aug": "août",
        "Sep": "septembre",
        "Oct": "octobre",
        "Nov": "novembre",
        "Dec": "décembre",
        "annotate_avg": "Température moyenne pour la période %d-1999 (station de %s)",
        "annotate_lastweek": "Température moyenne de la semaine passée",
        "source": "Source des données",
        "record": "nouveau record"
    },
    "de": {
        "title": "Die Durschschnitttemperatur der letzten 24 Stunden in %s war %.1f°C",
        "warm": "warm",
        "hot": "heiß",
        "very hot": ", sehr %s",
        "pretty hot": ", ziemlich %s",
        "average": ", im historischen Trend",
        "pretty cold": ", ziemlich kalt",
        "very cold": ", sehr kalt",
        "early": "Anfang ",
        "late": "Ende ",
        "mid": "Mitte ",
        "for month": " für %s%s",
        "Jan": "Januar",
        "Feb": "Februar",
        "Mar": "März",
        "Apr": "April",
        "May": "Mai",
        "Jun": "Juni",
        "Jul": "Juli",
        "Aug": "August",
        "Sep": "September",
        "Oct": "Oktober",
        "Nov": "November",
        "Dec": "Dezember",
        "annotate_avg": "%d-1999 Durchschnitttemperatur (%s Wetterstation)",
        "annotate_lastweek": "Durchschnitttemperatur der letzten Woche",
        "source": "Datenquellen",
        "record": "neuer Rekord"
    }
}