texts = {
    "en": {
        "title": "Historical context for temperatures in %s",
        "comment": "Average temperature in %s was %.1f°C over the last 24 hours,\n",
        "warm": "warm",
        "hot": "hot",
        "very hot": "very %s",
        "pretty hot": "pretty %s",
        "average": "about average",
        "pretty cold": "pretty cold",
        "very cold": "very cold",
        "early": "early ",
        "late": "late ",
        "mid": "mid-",
        "for month": " for %s%s",
        "Jan": "January",
        "Feb": "February",
        "Mar": "March",
        "Apr": "April",
        "May": "May",
        "Jun": "June",
        "Jul": "July",
        "Aug": "August",
        "Sep": "September",
        "Oct": "October",
        "Nov": "November",
        "Dec": "December",
        "annotate_avg": "%d-1999 average daily temperature (%s weather station)",
        "annotate_lastweek": "Average daily temperature for the last 7 days",
        "source": "Data source",
        "record": "new record",
        "answer": "@%s Here's the context data for %s you wanted! 🐕🐕"
    },
    "fr": {
        "title": "Contexte historique pour la température à %s",
        "comment": "La température moyenne à %s était de %.1f°C au cours des dernières 24 heures,\n",
        "warm": "doux",
        "hot": "chaud",
        "very hot": "très %s",
        "pretty hot": "assez %s",
        "average": "proche de la moyenne",
        "pretty cold": "plutôt froid",
        "very cold": "très froid",
        "early": "début ",
        "late": "fin ",
        "mid": "mi-",
        "for month": " pour %s%s",
        "Jan": "janvier",
        "Feb": "février",
        "Mar": "mars",
        "Apr": "avril",
        "May": "mai",
        "Jun": "juin",
        "Jul": "juillet",
        "Aug": "août",
        "Sep": "septembre",
        "Oct": "octobre",
        "Nov": "novembre",
        "Dec": "décembre",
        "annotate_avg": "Température moyenne pour la période %d-1999 (station de %s)",
        "annotate_lastweek": "Température moyenne journalière ces 7 derniers jours",
        "source": "Source des données",
        "record": "nouveau record",
        "answer": "@%s Et voilà le contexte météo pour %s ces 7 derniers jours! 🐕🐕"
    },
    "de": {
        "title": "Historischer Kontext für Temperaturen in %s",
        "comment": "Die Durchschnittstemperatur der letzten 24 Stunden in %s war %.1f°C,\n",
        "warm": "warm",
        "hot": "heiß",
        "very hot": "sehr %s",
        "pretty hot": "ziemlich %s",
        "average": "im historischen Trend",
        "pretty cold": "ziemlich kalt",
        "very cold": "sehr kalt",
        "early": "Anfang ",
        "late": "Ende ",
        "mid": "Mitte ",
        "for month": " für %s%s",
        "Jan": "Januar",
        "Feb": "Februar",
        "Mar": "März",
        "Apr": "April",
        "May": "Mai",
        "Jun": "Juni",
        "Jul": "Juli",
        "Aug": "August",
        "Sep": "September",
        "Oct": "Oktober",
        "Nov": "November",
        "Dec": "Dezember",
        "annotate_avg": "%d-1999 Durchschnittstemperatur (%s Wetterstation)",
        "annotate_lastweek": "Tägliche Durchschnittstemperatur der letzten 7 Tage",
        "source": "Datenquellen",
        "record": "neuer Rekord",
        "answer": "@%s Hier ist der Wetterkontext für %s! 🐕🐕"
    }
}